[package]
name = "rust-ml-serving"
version = "0.1.0"
authors = ["lain-m21 <lain21@mercari.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
